api:
  image:
    repository: course-mlops-api
    tag: latest
    pullPolicy: Never
  replicas: 1
  service:
    port: 8000
    type: NodePort
    nodePort: 30000

mlflow:
  image:
    repository: ghcr.io/mlflow/mlflow
    tag: v3.8.1
  replicas: 1
  service:
    type: NodePort
    port: 5000
    nodePort: 30001
  persistence:
    storageClass: ""
    size: 1Gi
    accessMode: ReadWriteOnce
